# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trelte-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trelte-common/proprietary/bin/argosd:system/bin/argosd \
    vendor/samsung/trelte-common/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/trelte-common/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/trelte-common/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/trelte-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/trelte-common/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_mfg.txt_a0:system/etc/wifi/nvram_mfg.txt_a0 \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_net.txt_a0:system/etc/wifi/nvram_net.txt_a0 \
    vendor/samsung/trelte-common/proprietary/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/trelte-common/proprietary/etc/sec_s3fwrn5_rfreg.bin:system/etc/sec_s3fwrn5_rfreg.bin \
    vendor/samsung/trelte-common/proprietary/lib/hw/nfc_nci.universal5433.so:system/lib/hw/nfc_nci.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/sec_s3fwrn5_firmware.bin:system/vendor/firmware/sec_s3fwrn5_firmware.bin \
    vendor/samsung/trelte-common/proprietary/lib/hw/consumerir.exynos5.so:system/lib/hw/consumerir.exynos5.so \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/hevc_fw.bin:system/vendor/firmware/hevc_fw.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_fw2_imx240.bin:system/vendor/firmware/fimc_is_fw2_imx240.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_ois_63A.bin:system/vendor/firmware/fimc_is_ois_63A.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/fimc_is_ois_63B.bin:system/vendor/firmware/fimc_is_ois_63B.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_default_coef.bin:system/vendor/firmware/companion_default_coef.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_default_lsc.bin:system/vendor/firmware/companion_default_lsc.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_fw_imx240_evt1.bin:system/vendor/firmware/companion_fw_imx240_evt1.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_imx240_master_setfile.bin:system/vendor/firmware/companion_imx240_master_setfile.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/companion_imx240_mode_setfile.bin:system/vendor/firmware/companion_imx240_mode_setfile.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp1-edac.bin:system/etc/firmware/florida-dsp1-edac.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp1-edac.wmfw:system/etc/firmware/florida-dsp1-edac.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.bin:system/etc/firmware/florida-dsp2-tx-fb-meeting.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw:system/etc/firmware/florida-dsp2-tx-fb-meeting.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-nb.wmfw:system/etc/firmware/florida-dsp2-tx-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-swb.wmfw:system/etc/firmware/florida-dsp2-tx-swb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp2-tx-wb.wmfw:system/etc/firmware/florida-dsp2-tx-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-ez2-control.wmfw:system/etc/firmware/florida-dsp3-ez2-control.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-lpsd-control.bin:system/etc/firmware/florida-dsp3-lpsd-control.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-nb.bin:system/etc/firmware/florida-dsp3-tx-nb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-nb.wmfw:system/etc/firmware/florida-dsp3-tx-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb-conversation.bin:system/etc/firmware/florida-dsp3-tx-swb-conversation.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb-interview.bin:system/etc/firmware/florida-dsp3-tx-swb-interview.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-swb.wmfw:system/etc/firmware/florida-dsp3-tx-swb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.bin:system/etc/firmware/florida-dsp3-tx-wb-meeting.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw:system/etc/firmware/florida-dsp3-tx-wb-meeting.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb.bin:system/etc/firmware/florida-dsp3-tx-wb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp3-tx-wb.wmfw:system/etc/firmware/florida-dsp3-tx-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-dsm.wmfw:system/etc/firmware/florida-dsp4-dsm.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.bin:system/etc/firmware/florida-dsp4-rx-anc-nb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-nb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-nb.wmfw \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.bin:system/etc/firmware/florida-dsp4-rx-anc-wb.bin \
    vendor/samsung/trelte-common/proprietary/etc/firmware/florida-dsp4-rx-anc-wb.wmfw:system/etc/firmware/florida-dsp4-rx-anc-wb.wmfw \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so \
    vendor/samsung/trelte-common/proprietary/lib/hw/camera.universal5433.so:system/lib/hw/camera.universal5433.so \
    vendor/samsung/trelte-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/trelte-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/trelte-common/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/trelte-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/setfile_6d1.bin:system/vendor/firmware/setfile_6d1.bin \
    vendor/samsung/trelte-common/proprietary/vendor/firmware/setfile_imx240.bin:system/vendor/firmware/setfile_imx240.bin \
    vendor/samsung/trelte-common/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/trelte-common/proprietary/lib/hw/gps.universal5433.so:system/lib/hw/gps.universal5433.so \
    vendor/samsung/trelte-common/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/trelte-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/hw/vulkan.exynos5.so:system/vendor/lib/hw/vulkan.exynos5.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libOpenCv.so:system/vendor/lib/libOpenCv.so \
    vendor/samsung/trelte-common/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/trelte-common/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/trelte-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/trelte-common/proprietary/etc/lhd.conf:system/etc/lhd.conf \
    vendor/samsung/trelte-common/proprietary/bin/lhd:system/bin/lhd \
    vendor/samsung/trelte-common/proprietary/lib/hw/sensors.universal5433.so:system/lib/hw/sensors.universal5433.so \
    vendor/samsung/trelte-common/proprietary/bin/sensorhubservice:system/bin/sensorhubservice \
    vendor/samsung/trelte-common/proprietary/lib/libgnustl_shared.so:system/lib/libgnustl_shared.so \
    vendor/samsung/trelte-common/proprietary/lib/libsensorhub.so:system/lib/libsensorhub.so \
    vendor/samsung/trelte-common/proprietary/lib/libsensorhubservice.so:system/lib/libsensorhubservice.so \
    vendor/samsung/trelte-common/proprietary/lib/hw/sensorhubs.universal5433.so:system/lib/hw/sensorhubs.universal5433.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/trelte-common/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/trelte-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/trelte-common/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so